service: webhook-service

plugins:
  - serverless-localstack
  - serverless-go-plugin

custom:
  localstack:
    stages:
      - local
    autostart: true
    docker:
      compose_file: docker/compose.yaml
    lambda:
      mount_code: true
    debug: true
  go:
    supportedRuntimes: ["provided.al2"]
    buildProvidedRuntimeAsBootstrap: true

provider:
  name: aws
  region: 'us-east-1'
  stage: ${opt:stage, 'local'}
  environment:
    APP_ENV: ${opt:stage, self:provider.stage}

functions:
  hello:
    handler: cmd/hello/main.go
    runtime: provided.al2
    events:
      - http:
          path: hello/{name}
          method: get
          cors: true
          request:
            parameters:
              paths:
                name: true

  hello-secondary:
    handler: cmd/hello-secondary/main.go
    runtime: provided.al2
    events:
      - http:
          path: hello-secondary/{name}
          method: get
          cors: true
          request:
            parameters:
              paths:
                name: true